### ISSUE TITLE
Popup is in the way when user selects an earthquake

### ISSUE THREAD

**Issue by boeckMt** [riesgos/dlr-riesgos-frontend#103]

**Comment by boeckMt** [comment]
![image](https://user-images.githubusercontent.com/3969484/157282340-0599c008-0595-4dcd-97a3-402e243a885b.png)
![image](https://user-images.githubusercontent.com/3969484/157282399-c6274fd4-8ece-46cc-8788-984c9c9c709e.png)

What exactly was the intention on making a feature bigger on a click (when select on map was not enabled)?

---
normally the selection should work, so it does at least one other UKIS-Apps.

**Comment by MichaelLangbein** [comment]
More details about the problem: 
 - when clicking on one eq, a popup appears. 
 - when user now wants to click on a eq nearby, this click does not always work
     - specifically, doesn't work when the eq is in the area right below the popup-body (but above the popup-triangle)
No longer an issue for Riesgos since we now do popups on hover.

**Comment by boeckMt** [comment]
The selection still doesn't work for me, I'll try to check the problem
