### ISSUE TITLE
Inclusion of 3rd party data

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#139]
Examples of data to be included:
Better administrative borders for Peru:
https://sit.icl.gob.pe/sit_app/
https://sigrid.cenepred.gob.pe 
https://geo.vivienda.gob.pe/

**Comment by MichaelLangbein** [comment]
None of the above worked for me, unfortunately. 

 - https://sit.icl.gob.pe/sit_app/ <= ArcGIS with credentials only
 - https://sigrid.cenepred.gob.pe  <= Login doesn't work
 - https://geo.vivienda.gob.pe/ <= ArcGIS with credentials only

**Comment by boeckMt** [comment]
for the first (https://sit.icl.gob.pe/sit_app/) I get borders for Lima https://sit.icl.gob.pe/arcgis/rest/services/AGOL_Servicios/LIMA_METROPOLITANA/MapServer/export?dpi=96&transparent=true&format=png32&layers=show%3A300%2C301&bbox=-8612009.02327189%2C-1394997.9080893628%2C-8537253.609609088%2C-1323070.6644731087&bboxSR=102100&imageSR=102100&size=978%2C941&f=image

---

on the second I found:
- https://sigrid.cenepred.gob.pe/sigridv3/evar
- https://sigrid.cenepred.gob.pe/sigridv3/pprrd

but these are included in google maps so no service we can use easily.

---

on the third I found:
- https://dportalgis.vivienda.gob.pe/dfdserver/rest/services/EXTERNAS/16_CENEPRED/MapServer/export?dpi=96&transparent=true&format=png32&layers=show%3A-1%2C-1%2C-1%2C1&bbox=-8847503.663706165%2C-1948375.5392602636%2C-7700336.743202545%2C-779194.7546105185&bboxSR=102100&imageSR=102100&size=938%2C956&f=image
- https://dportalgis.vivienda.gob.pe/dfdserver/rest/services/OGEI/limites_peru/MapServer/export?dynamicLayers=%5B%7B%22id%22%3A6%2C%22name%22%3A%22Departamentos%22%2C%22source%22%3A%7B%22type%22%3A%22mapLayer%22%2C%22mapLayerId%22%3A6%7D%2C%22minScale%22%3A399999999.99999994%2C%22maxScale%22%3A0%7D%5D&dpi=96&transparent=true&format=png32&bbox=-8515461.21283552%2C-1790609.5128797358%2C-7941877.752583586%2C-1206019.1205547368&bboxSR=102100&imageSR=102100&size=938%2C956&f=image
