### ISSUE TITLE
Ashfall: strange pattern of damage

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#146]
Why was there a narrow 'corridor' of damage through ashfall even though our ashfall-polygons are actually much more spread out? 
![screenshot](https://user-images.githubusercontent.com/13807050/164542443-bc3ae56c-f593-4cf2-89da-258a2f3d29b9.PNG)

 - Fragility curves used to be lognormals - now adjusted to normals in accordance to literature.
 - AshfallPoint data was too high by a factor of 100 (!). Did assume ash-depth to be given in m, really was in centimeter. Has been adjusted. With such a significantly lower load, no damage-patterns can be discerned any more ... but they might still be there.
 
It's still worth investigating where the previous, odd patterns in damage came from.

**Comment by MichaelLangbein** [comment]
Could this be a projection error?

**Comment by MichaelLangbein** [comment]
Point data orignally from IGEPN
- but: load parameter darived from depth
Polygons derived from point data

**Comment by MichaelLangbein** [comment]
This was figured out by @nbrinckm in a truely Sherlock Holmsian fashion. 
Input file contained a property named 'id' - with *non-unique* entries. 
When parsing this file, deus would discard features that had an already seen id; massively reducing the amount of data that was used for damage-estimation.

**Comment by nbrinckm** [comment]
Just for completion: This was not an issue with Deus, but with the default geojson parser that was delivered with the WPS server (Deus itfself is stupid enough not do this filtering - which madebit even harder to find out)
