### ISSUE TITLE
Frontend: allow process to appear multiple times

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#20]
DEUS and Reliability-Service need to be called mutliple times. Accomodate that in frontend.

**Comment by MichaelLangbein** [comment]
Atm, our Frontend creates a graph of processes and products. It arranges them linearly using toposort. However, a topological order is only possible iff the graph is a DAG. This is problematic, since having a process be run multiple times introduces circles.

- option 1 is to just duplicate the process with another id.
- option 2 would be to include the information that every edge in the graph may only be passed through once. (Never done that before, will do research on this.)

**Comment by nmandery** [comment]
Maybe a simple solution: Do not use the name of the process implementation for the graph node, but instead use a description of the goal that should be achieved.

**Comment by MichaelLangbein** [comment]
Really, I was being silly here. What we're looking for here is a (hamiltonian) walk through the graph, not an order of the nodes.
