### ISSUE TITLE
Integrate DEUS into Ecuador Scenario for Lahar-damage

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#34]
1. Lahar Service needs to also output it's results as a GeoTiff-file of Lahar-height (TUM/eomap)
2. That geotiff will then be fed into DEUS (DLR)

**Comment by sabinehelm** [comment]
The Lahar Service now also returns the Lahar parameter in shakemap xml format to be fed into DEUS.
(It was agreed to use Geotiff or shakemap - now shakemap was implemented)
