### ISSUE TITLE
A few Layout and functional Enhancements

### ISSUE THREAD

**Issue by boeckMt** [riesgos/dlr-riesgos-frontend#51]
1. - [x] The CSS layout doesn't quite fit on the intro page. There are two scroll bars that shouldn't be there and the RIESGOS logo is cut off. The  scroll bars come when you change the language.

![image](https://user-images.githubusercontent.com/3969484/119468161-7b5d3b00-bd46-11eb-9af0-20285870b8a7.png)

---

2. - [x] The Licenses page is out of date (see versions in https://github.com/riesgos/dlr-riesgos-frontend/blob/master/package.json)

---

3. - [ ]  If you change the language to English on the intro page and then click on one of the stories, the language changes back to Spanish

---

4. - [x]  In the Configuration Wizard, the badges are cut off when one of the "nav-group" elements is open
![image](https://user-images.githubusercontent.com/3969484/119469288-7fd62380-bd47-11eb-960d-5cbbf6fb6dfa.png)

---

5. - [ ]  After the Shakemap was added (this also applies to other layers), the map strangely stops responding

---

6. - [x] The exposure graphs are partly "empty", if no data is available for these elements I would not show the graph but only show a short text like "No Data" or something.
![image](https://user-images.githubusercontent.com/3969484/119470090-4520bb00-bd48-11eb-8a7c-0cc951e95a5d.png)

---

7. - [x] When the side navigations are collapsed, the title should disappear and an icon should appear for it instead
![image](https://user-images.githubusercontent.com/3969484/119470323-84e7a280-bd48-11eb-9259-e562b8e640d8.png)

---

8. - [x] When saving the layer compilation as JSON I would try to intercept the file name so that there are no symbols in the name that should not be used in file names

**Comment by MichaelLangbein** [comment]
Alright, fixed most of these issues: https://github.com/riesgos/dlr-riesgos-frontend/releases/tag/v1.4 and https://github.com/riesgos/dlr-riesgos-frontend/releases/tag/v1.4_chile

For those that are going to take a little longer, i created separate issues: https://github.com/riesgos/dlr-riesgos-frontend/issues/54 and https://github.com/riesgos/dlr-riesgos-frontend/issues/53
