### ISSUE TITLE
Right sidebar not adjusting to screen size

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#70]

**Comment by boeckMt** [comment]
This is not as easy as expected, unfortunately the color theme switch changed some selectors.
Have to find a solution for this.

**Comment by boeckMt** [comment]
- https://juristr.com/blog/2019/08/dynamically-load-css-angular-cli/

**Comment by MichaelLangbein** [comment]
If this should not work within the timeframe of this sprint, we'll just increase the size of the right sidebar to be equal to the left.
Also, both sidebars should ideally be size-adjustable.

**Comment by boeckMt** [comment]
should be fixed with c33acbd21a0c97a0664f5e3e674fc8cf8da7c5fa but in the future we should try to use the new clarity way to style themes.

**Comment by MichaelLangbein** [comment]
Fixed with merge.
