### ISSUE TITLE
TypeError: on create_custom_layer 

### ISSUE THREAD

**Issue by boeckMt** [riesgos/dlr-riesgos-frontend#97]
at h.create_custom_layer (main.93433376d2586e7a8375.js:1:8117323)
    at h.create_layers (main.93433376d2586e7a8375.js:1:8107994)
    at main.93433376d2586e7a8375.js:1:8107139
    at Array.forEach (<anonymous>)
    at h.setUkisLayers (main.93433376d2586e7a8375.js:1:8107114)
    at h.addUpdateLayers (main.93433376d2586e7a8375.js:1:8131666)
    at R._next (main.93433376d2586e7a8375.js:1:8135293)
    at R.__tryOrUnsub (main.93433376d2586e7a8375.js:1:7068456)
    at R.next (main.93433376d2586e7a8375.js:1:7067697)
    at L._next (main.93433376d2586e7a8375.js:1:7066893)

---

@MichaelLangbein  when exactly does this happen ?

The problem here is that the custom layer you are create do not have a source. See https://github.com/dlr-eoc/ukis-frontend-libraries/blob/966e87c70478f155bc027e25adf19ab85d6eeb7f/projects/map-ol/src/lib/map-ol.service.ts#L1477

**Comment by MichaelLangbein** [comment]
Reproducing the error: 
- execute catalogue service
- click on "reiniciar" (bottom right of screen)
- execute catalogue service again <= no data displayed

**Comment by MichaelLangbein** [comment]
Appears to be fixed by https://github.com/riesgos/dlr-riesgos-frontend/commit/db8d56b3174f5c99abb69c70ce09c9d7408a6a7c
But I don't really see how this works. Needs further investigation

**Comment by boeckMt** [comment]
> Appears to be fixed by [db8d56b](https://github.com/riesgos/dlr-riesgos-frontend/commit/db8d56b3174f5c99abb69c70ce09c9d7408a6a7c) But I don't really see how this works. Needs further investigation

Does these changes somehow create a new layer? The only difference I can see is that you use constants now instead of classes.

**Comment by MichaelLangbein** [comment]
> > Appears to be fixed by [db8d56b](https://github.com/riesgos/dlr-riesgos-frontend/commit/db8d56b3174f5c99abb69c70ce09c9d7408a6a7c) But I don't really see how this works. Needs further investigation
> 
> Does these changes somehow create a new layer? The only difference I can see is that you use constants now instead of classes.

That is indeed the only difference. 
Just out of the top of my head this might have to do with ngrx-reducers creating copies of the current state any time they are called. Maybe that works better with raw objects instead of class instances; I.e. on objects without a long prototype-chain. But really this is just a thought.

**Comment by MichaelLangbein** [comment]
Just had the issue appear again. To reproduce:
- Peru scenario. 
- Get exposure data.
- Re-configure exposure-service.
- Get exposure data again.

**Comment by MichaelLangbein** [comment]
Might be a cache issue. Data is serialized to be stored in cache. Can then not be properly restored from string.

**Comment by MichaelLangbein** [comment]
> Might be a cache issue. Data is serialized to be stored in cache. Can then not be properly restored from string.

Removed cache from layer_marshaller: https://github.com/riesgos/dlr-riesgos-frontend/commit/fff15e9e3ae5b91e1df901971db517936e2ae826 

This might address our issue - even though that removal was for a different reason: we cannot afford to keep old layers in memory; are severely memory limited already. 

Please re-open if issue occurs anew.
