### ISSUE TITLE
Placement for app alert as disclaimer

### ISSUE THREAD

**Issue by boeckMt** [riesgos/dlr-riesgos-frontend#98]
#### 1. Originally the alert was placed in the header, this caused an unwanted overflow on smaller display sizes.
![image](https://user-images.githubusercontent.com/3969484/157199766-5739eac6-4d3a-4986-90bb-65d02d1fe2c0.png)

- https://github.com/vmware/clarity/issues/1445

#### 2. Unfortunately the usage of the top Level alert is not welcomed by the project management, because it can be removed more easily on a screenshot.
![image](https://user-images.githubusercontent.com/3969484/157200611-9e9d620f-f49d-4e93-bb50-8580eaf86ddf.png)

**Comment by boeckMt** [comment]
New implementation place alert below the header.  This is not like proposed from the clarity layout, but in this way it cannot be cut off so easily of a screenshot

![image](https://user-images.githubusercontent.com/3969484/157224797-5eb47f54-bb43-430b-99c3-035ccd9031bb.png)


---

In the header it would be looking like following

![image](https://user-images.githubusercontent.com/3969484/157225550-b4dce01a-af48-4b12-a98d-c6a4f79f0d22.png)
![image](https://user-images.githubusercontent.com/3969484/157225661-ff94baf9-3521-4a55-9c1d-cdfd6236f072.png)

**Comment by MichaelLangbein** [comment]
Resolved with PR.
